/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ISymmioPartyA,
  ISymmioPartyAInterface,
} from "../../../contracts/interfaces/ISymmioPartyA";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "_approve",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "_callData",
        type: "bytes",
      },
    ],
    name: "_call",
    outputs: [
      {
        internalType: "bool",
        name: "_success",
        type: "bool",
      },
      {
        internalType: "bytes",
        name: "_resultData",
        type: "bytes",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "withdrawERC20",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ISymmioPartyA__factory {
  static readonly abi = _abi;
  static createInterface(): ISymmioPartyAInterface {
    return new utils.Interface(_abi) as ISymmioPartyAInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISymmioPartyA {
    return new Contract(address, _abi, signerOrProvider) as ISymmioPartyA;
  }
}
