/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IMultiAccount } from "./IMultiAccount";
export type { ISymmio } from "./ISymmio";
export type { ISymmioPartyA } from "./ISymmioPartyA";
